"""ISSUE-059: Add create_behavior() factory pseudo-code to section 3.2"""
path = 'docs/01-活跃/subsystems/保底系统/P55 保底体系重构——正交分解与Context驱动的独立保底架构.md'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

anchor = '**CounterBasedBehavior._rebind_state() 实现：**'

new_block = (
    '<!-- REVIEW-R2-FIX: ISSUE-059 -->\n'
    '#### 3.2.0 create_behavior() 工厂函数——P55 更新版\n'
    '\n'
    'P60 的 `create_behavior()`（`pity.py:343-372`）从 `BEHAVIOR_REGISTRY` 的 `default_scope` 读取 scope、'
    '从 `pdef.params` dict 读取参数并做类型转换——两者在 P55 中均不兼容：'
    '(1) scope 是 per-behavior 配置字段（`PityDef.scope`），必须从 PityDef 实例读取而非 registry 默认值；'
    '(2) P55 的 `PityDef` 已扁平化，`params` dict 不存在，所有参数从 PityDef 平级字段读取。\n'
    '\n'
    '```python\n'
    'def create_behavior(name: str, state: \'PityState\', pdef: \'PityDef\') -> \'PityBehavior\':\n'
    '    """P55 新版工厂：按 btype 分发，从 PityDef 平级字段读取参数。\n'
    '\n'
    '    P60 旧签名 `create_behavior(pdef: PityDefParsed, state, **extra)` 已废弃——\n'
    '    P55 中 PityDefParsed 被 PityDef 替代，scope 从 registry default_scope 改为 per-instance 读取。\n'
    '    """\n'
    '    entry = BEHAVIOR_REGISTRY[pdef.btype]\n'
    '    cls = entry["class"]\n'
    '    scope = pdef.scope  # ← P55 变更：从 PityDef 实例读取，非 registry default_scope\n'
    '\n'
    '    # ── 生命周期构造（从 PityDef 平级字段） ──\n'
    '    lifecycle = LifecycleConfig(\n'
    '        max_triggers=pdef.max_triggers,\n'
    '        deactivate_on_early_hit=pdef.deactivate_on_early_hit,\n'
    '        depends_on=pdef.depends_on,\n'
    '    )\n'
    '\n'
    '    # ── 按 btype 分发到具体 behavior 类 ──\n'
    '    if pdef.btype in SOFT_TYPES:\n'
    '        # soft_interval / soft_additive / soft_step → SoftStepBehavior\n'
    '        return SoftStepBehavior(\n'
    '            name=name, state=state, scope=scope, btype=pdef.btype,\n'
    '            deltas=pdef.deltas,  # 语法糖已在 _build_pity_def() 中展开\n'
    '            target_featured=pdef.target_featured,\n'
    '            lifecycle=lifecycle,\n'
    '        )\n'
    '\n'
    '    if pdef.btype == \'hard\':\n'
    '        return HardPityBehavior(\n'
    '            name=name, state=state, scope=scope, btype=pdef.btype,\n'
    '            threshold=pdef.threshold,\n'
    '            counter_init=pdef.counter_init,\n'
    '            target_featured=pdef.target_featured,\n'
    '            lifecycle=lifecycle,\n'
    '        )\n'
    '\n'
    '    if pdef.btype in (\'rotating\', \'rotating_soft\'):\n'
    '        return RotatingBehavior(\n'
    '            name=name, state=state, scope=scope, btype=pdef.btype,\n'
    '            counter_init=pdef.counter_init,\n'
    '            guaranteed_init=pdef.guaranteed_init,\n'
    '            target_featured=pdef.target_featured,\n'
    '            soft_start=pdef.soft_start,\n'
    '            soft_end=pdef.soft_end,\n'
    '            soft_increment=pdef.soft_increment,\n'
    '            soft_deltas=pdef.soft_deltas,\n'
    '            lifecycle=lifecycle,\n'
    '        )\n'
    '\n'
    '    if pdef.btype in (\'rotating_cr\', \'rotating_cr_soft\'):\n'
    '        return RotatingCRBehavior(\n'
    '            name=name, state=state, scope=scope, btype=pdef.btype,\n'
    '            counter_init=pdef.counter_init,\n'
    '            guaranteed_init=pdef.guaranteed_init,\n'
    '            cr_counter_threshold=pdef.cr_counter_threshold,\n'
    '            cr_base_rate=pdef.cr_base_rate,\n'
    '            cr_state_probs=pdef.cr_state_probs,\n'
    '            soft_start=pdef.soft_start,\n'
    '            soft_end=pdef.soft_end,\n'
    '            soft_increment=pdef.soft_increment,\n'
    '            soft_deltas=pdef.soft_deltas,\n'
    '            lifecycle=lifecycle,\n'
    '        )\n'
    '\n'
    '    if pdef.btype in (\'targeted\', \'targeted_soft\'):\n'
    '        return TargetedBehavior(\n'
    '            name=name, state=state, scope=scope, btype=pdef.btype,\n'
    '            counter_init=pdef.counter_init,\n'
    '            fate_points_init=pdef.fate_points_init,\n'
    '            fate_threshold=pdef.fate_threshold,\n'
    '            switch_allowed=pdef.switch_allowed,\n'
    '            switch_resets_progress=pdef.switch_resets_progress,\n'
    '            soft_start=pdef.soft_start,\n'
    '            soft_end=pdef.soft_end,\n'
    '            soft_increment=pdef.soft_increment,\n'
    '            soft_deltas=pdef.soft_deltas,\n'
    '            lifecycle=lifecycle,\n'
    '        )\n'
    '\n'
    '    raise ConfigError(f"未知的保底类型: {pdef.btype}")\n'
    '```\n'
    '\n'
    '**关键变更（与 P60 `create_behavior()` 对比）：**\n'
    '- **scope 来源：** `pdef.scope`（per-behavior 配置）取代 `BEHAVIOR_REGISTRY[].default_scope`。\n'
    '- **参数来源：** `PityDef` 平级字段（`deltas`/`threshold`/`counter_init`/`soft_start` 等）取代 `pdef.params` dict。\n'
    '- **LifecycleConfig 构造：** 从 PityDef 的 `max_triggers`/`deactivate_on_early_hit`/`depends_on` 平级字段构造。\n'
    '- **类型转换：** 不再需要——`PityDef` 字段类型已在 `_build_pity_def()` 解析阶段完成校验和转换。\n'
    '<!-- /REVIEW-R2-FIX: ISSUE-059 -->\n'
    '\n'
)

content = content.replace(anchor, new_block + anchor)
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Done')
